Update to work with gcc 15. We needed to update libtool and autools, we got an obscure linking error (undefined reference to '__TMC_END__'). Not clear why exactly, but updating the autotools configure etc. fixed this problem. We now compile with gcc 15 cleanly.